# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QSpinBox, QTextBrowser, QToolButton, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(560, 603)
        self.lineEdit_ip_addr = QLineEdit(Widget)
        self.lineEdit_ip_addr.setObjectName(u"lineEdit_ip_addr")
        self.lineEdit_ip_addr.setGeometry(QRect(160, 50, 161, 31))
        font = QFont()
        font.setFamilies([u"Helvetica"])
        self.lineEdit_ip_addr.setFont(font)
        self.lineEdit_ip_addr.setMaxLength(15)
        self.lineEdit_ip_addr.setFrame(True)
        self.lineEdit_ip_addr.setCursorPosition(0)
        self.lineEdit_ip_addr.setAlignment(Qt.AlignCenter)
        self.lineEdit_ip_addr.setClearButtonEnabled(False)
        self.lineEdit_port = QLineEdit(Widget)
        self.lineEdit_port.setObjectName(u"lineEdit_port")
        self.lineEdit_port.setGeometry(QRect(440, 50, 81, 31))
        self.lineEdit_port.setFont(font)
        self.lineEdit_port.setMaxLength(5)
        self.lineEdit_port.setCursorPosition(0)
        self.lineEdit_port.setAlignment(Qt.AlignCenter)
        self.pushButton_generate = QPushButton(Widget)
        self.pushButton_generate.setObjectName(u"pushButton_generate")
        self.pushButton_generate.setGeometry(QRect(440, 370, 100, 51))
        font1 = QFont()
        font1.setFamilies([u"Helvetica"])
        font1.setPointSize(15)
        font1.setBold(False)
        self.pushButton_generate.setFont(font1)
        self.toolButton_save_path = QToolButton(Widget)
        self.toolButton_save_path.setObjectName(u"toolButton_save_path")
        self.toolButton_save_path.setGeometry(QRect(510, 200, 26, 31))
        self.toolButton_save_path.setFont(font)
        self.checkBox_arch = QCheckBox(Widget)
        self.checkBox_arch.setObjectName(u"checkBox_arch")
        self.checkBox_arch.setGeometry(QRect(20, 290, 181, 20))
        font2 = QFont()
        font2.setFamilies([u"Helvetica"])
        font2.setPointSize(13)
        self.checkBox_arch.setFont(font2)
        self.comboBox_payload_type = QComboBox(Widget)
        self.comboBox_payload_type.setObjectName(u"comboBox_payload_type")
        self.comboBox_payload_type.setGeometry(QRect(10, 120, 531, 51))
        self.comboBox_payload_type.setFont(font)
        self.comboBox_payload_type.setEditable(False)
        self.comboBox_payload_type.setDuplicatesEnabled(False)
        self.label_ip_addr = QLabel(Widget)
        self.label_ip_addr.setObjectName(u"label_ip_addr")
        self.label_ip_addr.setGeometry(QRect(20, 50, 131, 31))
        font3 = QFont()
        font3.setFamilies([u"Helvetica"])
        font3.setPointSize(15)
        self.label_ip_addr.setFont(font3)
        self.label_port = QLabel(Widget)
        self.label_port.setObjectName(u"label_port")
        self.label_port.setGeometry(QRect(350, 50, 91, 31))
        self.label_port.setFont(font3)
        self.line_2 = QFrame(Widget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(340, 100, 211, 20))
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_section_ip_addr = QLabel(Widget)
        self.label_section_ip_addr.setObjectName(u"label_section_ip_addr")
        self.label_section_ip_addr.setGeometry(QRect(10, 15, 301, 21))
        font4 = QFont()
        font4.setFamilies([u"Helvetica"])
        font4.setPointSize(18)
        self.label_section_ip_addr.setFont(font4)
        self.line_1 = QFrame(Widget)
        self.line_1.setObjectName(u"line_1")
        self.line_1.setGeometry(QRect(240, 15, 311, 21))
        self.line_1.setFont(font)
        self.line_1.setFrameShape(QFrame.HLine)
        self.line_1.setFrameShadow(QFrame.Sunken)
        self.label_section_payload_main = QLabel(Widget)
        self.label_section_payload_main.setObjectName(u"label_section_payload_main")
        self.label_section_payload_main.setGeometry(QRect(10, 100, 321, 21))
        self.label_section_payload_main.setFont(font4)
        self.comboBox_encoder = QComboBox(Widget)
        self.comboBox_encoder.setObjectName(u"comboBox_encoder")
        self.comboBox_encoder.setGeometry(QRect(160, 160, 181, 41))
        self.comboBox_encoder.setFont(font)
        self.comboBox_format = QComboBox(Widget)
        self.comboBox_format.setObjectName(u"comboBox_format")
        self.comboBox_format.setGeometry(QRect(340, 160, 201, 41))
        self.comboBox_format.setFont(font)
        self.comboBox_platform = QComboBox(Widget)
        self.comboBox_platform.setObjectName(u"comboBox_platform")
        self.comboBox_platform.setGeometry(QRect(10, 160, 151, 41))
        self.comboBox_platform.setFont(font)
        self.comboBox_arch = QComboBox(Widget)
        self.comboBox_arch.addItem("")
        self.comboBox_arch.setObjectName(u"comboBox_arch")
        self.comboBox_arch.setEnabled(False)
        self.comboBox_arch.setGeometry(QRect(200, 290, 121, 21))
        self.comboBox_arch.setFont(font)
        self.lineEdit_save_path = QLineEdit(Widget)
        self.lineEdit_save_path.setObjectName(u"lineEdit_save_path")
        self.lineEdit_save_path.setGeometry(QRect(180, 200, 331, 31))
        font5 = QFont()
        font5.setFamilies([u"Helvetica"])
        font5.setPointSize(15)
        font5.setItalic(True)
        self.lineEdit_save_path.setFont(font5)
        self.lineEdit_save_path.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_save_path.setReadOnly(True)
        self.lineEdit_save_path.setClearButtonEnabled(False)
        self.label_save_path = QLabel(Widget)
        self.label_save_path.setObjectName(u"label_save_path")
        self.label_save_path.setGeometry(QRect(20, 200, 161, 31))
        self.label_save_path.setFont(font3)
        self.label_section_payload_sub = QLabel(Widget)
        self.label_section_payload_sub.setObjectName(u"label_section_payload_sub")
        self.label_section_payload_sub.setGeometry(QRect(10, 250, 361, 21))
        self.label_section_payload_sub.setFont(font4)
        self.line_3 = QFrame(Widget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(370, 250, 181, 20))
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.checkBox_smallest = QCheckBox(Widget)
        self.checkBox_smallest.setObjectName(u"checkBox_smallest")
        self.checkBox_smallest.setGeometry(QRect(20, 320, 171, 20))
        self.checkBox_smallest.setFont(font2)
        self.checkBox_iteration = QCheckBox(Widget)
        self.checkBox_iteration.setObjectName(u"checkBox_iteration")
        self.checkBox_iteration.setGeometry(QRect(340, 290, 131, 20))
        self.checkBox_iteration.setFont(font2)
        self.label_iteration = QLabel(Widget)
        self.label_iteration.setObjectName(u"label_iteration")
        self.label_iteration.setGeometry(QRect(530, 290, 21, 21))
        self.label_iteration.setFont(font)
        self.line_4 = QFrame(Widget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(10, 350, 541, 21))
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.comboBox_encrypt = QComboBox(Widget)
        self.comboBox_encrypt.addItem("")
        self.comboBox_encrypt.addItem("")
        self.comboBox_encrypt.addItem("")
        self.comboBox_encrypt.addItem("")
        self.comboBox_encrypt.addItem("")
        self.comboBox_encrypt.setObjectName(u"comboBox_encrypt")
        self.comboBox_encrypt.setEnabled(False)
        self.comboBox_encrypt.setGeometry(QRect(360, 320, 81, 21))
        self.comboBox_encrypt.setFont(font)
        self.checkBox_encrypt = QCheckBox(Widget)
        self.checkBox_encrypt.setObjectName(u"checkBox_encrypt")
        self.checkBox_encrypt.setGeometry(QRect(190, 320, 181, 20))
        self.checkBox_encrypt.setFont(font2)
        self.toolButton_key = QToolButton(Widget)
        self.toolButton_key.setObjectName(u"toolButton_key")
        self.toolButton_key.setEnabled(False)
        self.toolButton_key.setGeometry(QRect(440, 320, 101, 21))
        self.toolButton_key.setFont(font)
        self.label_key = QLabel(Widget)
        self.label_key.setObjectName(u"label_key")
        self.label_key.setGeometry(QRect(440, 320, 101, 21))
        self.label_key.setFont(font2)
        self.label_key.setAlignment(Qt.AlignCenter)
        self.textBrowser_output = QTextBrowser(Widget)
        self.textBrowser_output.setObjectName(u"textBrowser_output")
        self.textBrowser_output.setGeometry(QRect(10, 430, 541, 161))
        self.textBrowser_output.setFont(font)
        self.lineEdit_file_name = QLineEdit(Widget)
        self.lineEdit_file_name.setObjectName(u"lineEdit_file_name")
        self.lineEdit_file_name.setEnabled(True)
        self.lineEdit_file_name.setGeometry(QRect(150, 380, 161, 31))
        self.lineEdit_file_name.setFont(font3)
        self.lineEdit_file_name.setAlignment(Qt.AlignCenter)
        self.spinBox_count = QSpinBox(Widget)
        self.spinBox_count.setObjectName(u"spinBox_count")
        self.spinBox_count.setGeometry(QRect(370, 380, 42, 31))
        self.spinBox_count.setFont(font)
        self.spinBox_count.setAlignment(Qt.AlignCenter)
        self.spinBox_count.setMinimum(1)
        self.label_count = QLabel(Widget)
        self.label_count.setObjectName(u"label_count")
        self.label_count.setGeometry(QRect(330, 380, 41, 31))
        self.label_count.setFont(font)
        self.spinBox_iteration = QSpinBox(Widget)
        self.spinBox_iteration.setObjectName(u"spinBox_iteration")
        self.spinBox_iteration.setEnabled(False)
        self.spinBox_iteration.setGeometry(QRect(470, 290, 61, 22))
        self.spinBox_iteration.setFont(font)
        self.spinBox_iteration.setAlignment(Qt.AlignCenter)
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 380, 131, 31))
        self.label.setFont(font3)
        self.line_4.raise_()
        self.lineEdit_ip_addr.raise_()
        self.lineEdit_port.raise_()
        self.pushButton_generate.raise_()
        self.toolButton_save_path.raise_()
        self.checkBox_arch.raise_()
        self.comboBox_payload_type.raise_()
        self.label_ip_addr.raise_()
        self.label_port.raise_()
        self.line_2.raise_()
        self.label_section_ip_addr.raise_()
        self.line_1.raise_()
        self.label_section_payload_main.raise_()
        self.comboBox_encoder.raise_()
        self.comboBox_format.raise_()
        self.comboBox_platform.raise_()
        self.comboBox_arch.raise_()
        self.lineEdit_save_path.raise_()
        self.label_save_path.raise_()
        self.label_section_payload_sub.raise_()
        self.line_3.raise_()
        self.checkBox_smallest.raise_()
        self.checkBox_iteration.raise_()
        self.label_iteration.raise_()
        self.comboBox_encrypt.raise_()
        self.checkBox_encrypt.raise_()
        self.toolButton_key.raise_()
        self.label_key.raise_()
        self.textBrowser_output.raise_()
        self.lineEdit_file_name.raise_()
        self.spinBox_count.raise_()
        self.label_count.raise_()
        self.spinBox_iteration.raise_()
        self.label.raise_()

        self.retranslateUi(Widget)
        self.checkBox_arch.toggled.connect(self.comboBox_arch.setEnabled)
        self.checkBox_encrypt.toggled.connect(self.comboBox_encrypt.setEnabled)
        self.checkBox_encrypt.toggled.connect(self.toolButton_key.setEnabled)
        self.checkBox_iteration.toggled.connect(self.spinBox_iteration.setEnabled)

        self.comboBox_payload_type.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"\u65e0\u635f\u5316\u6d4b\u8bd5\u7528\u4f8b\u751f\u6210\u5de5\u5177", None))
        self.lineEdit_ip_addr.setInputMask(QCoreApplication.translate("Widget", u"000.000.000.000", None))
        self.lineEdit_ip_addr.setText(QCoreApplication.translate("Widget", u"...", None))
        self.lineEdit_port.setInputMask(QCoreApplication.translate("Widget", u"00000", None))
        self.lineEdit_port.setText(QCoreApplication.translate("Widget", u"4444", None))
        self.pushButton_generate.setText(QCoreApplication.translate("Widget", u"Generate", None))
        self.toolButton_save_path.setText(QCoreApplication.translate("Widget", u"...", None))
        self.checkBox_arch.setText(QCoreApplication.translate("Widget", u"Specify Target Architecture:", None))
        self.comboBox_payload_type.setCurrentText("")
        self.comboBox_payload_type.setPlaceholderText(QCoreApplication.translate("Widget", u"Payload type...", None))
        self.label_ip_addr.setText(QCoreApplication.translate("Widget", u"Listener IP Address", None))
        self.label_port.setText(QCoreApplication.translate("Widget", u"Listener Port", None))
        self.label_section_ip_addr.setText(QCoreApplication.translate("Widget", u"Listener-Side Configuration", None))
        self.label_section_payload_main.setText(QCoreApplication.translate("Widget", u"Payload Main Parameters Configuration", None))
        self.comboBox_encoder.setCurrentText("")
        self.comboBox_encoder.setPlaceholderText(QCoreApplication.translate("Widget", u"Encoder...", None))
        self.comboBox_format.setPlaceholderText(QCoreApplication.translate("Widget", u"Format...", None))
        self.comboBox_platform.setCurrentText("")
        self.comboBox_platform.setPlaceholderText(QCoreApplication.translate("Widget", u"Platform...", None))
        self.comboBox_arch.setItemText(0, "")

        self.lineEdit_save_path.setInputMask("")
        self.lineEdit_save_path.setText("")
        self.lineEdit_save_path.setPlaceholderText(QCoreApplication.translate("Widget", u"Please Choose the Save Path", None))
        self.label_save_path.setText(QCoreApplication.translate("Widget", u"Payload File Save Path", None))
        self.label_section_payload_sub.setText(QCoreApplication.translate("Widget", u"Payload Addtional Parameters Configuration", None))
        self.checkBox_smallest.setText(QCoreApplication.translate("Widget", u"Enable Smallest Encode", None))
        self.checkBox_iteration.setText(QCoreApplication.translate("Widget", u"Specify Iterations:", None))
        self.label_iteration.setText("")
        self.comboBox_encrypt.setItemText(0, "")
        self.comboBox_encrypt.setItemText(1, QCoreApplication.translate("Widget", u"AES256", None))
        self.comboBox_encrypt.setItemText(2, QCoreApplication.translate("Widget", u"base64", None))
        self.comboBox_encrypt.setItemText(3, QCoreApplication.translate("Widget", u"RC4", None))
        self.comboBox_encrypt.setItemText(4, QCoreApplication.translate("Widget", u"XOR", None))

        self.checkBox_encrypt.setText(QCoreApplication.translate("Widget", u"Enable Session Encryption", None))
        self.toolButton_key.setText(QCoreApplication.translate("Widget", u"...", None))
        self.label_key.setText(QCoreApplication.translate("Widget", u"Upload key file", None))
        self.lineEdit_file_name.setText("")
        self.lineEdit_file_name.setPlaceholderText(QCoreApplication.translate("Widget", u"sample.exe", None))
        self.label_count.setText(QCoreApplication.translate("Widget", u"Count:", None))
        self.label.setText(QCoreApplication.translate("Widget", u"Payload File Name", None))
    # retranslateUi

